# Copyright (C) 2015-2017 Libre Informatique
#
# This file is licenced under the GNU GPL v3.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

sylius_user:
    driver: doctrine/orm
    resources:
        sonata:
            user:
                classes:
                    model: Sil\Bundle\SonataSyliusUserBundle\Entity\SonataUser
                    repository: Sylius\Bundle\UserBundle\Doctrine\ORM\UserRepository
                    # TODO:
                    form: Sylius\Bundle\CoreBundle\Form\Type\User\AdminUserType
                    interface: Sylius\Component\User\Model\UserInterface
                    controller: Sylius\Bundle\UserBundle\Controller\UserController
                    factory: Sylius\Component\Resource\Factory\Factory
                templates: 'SyliusUserBundle:User'
                resetting:
                    token:
                        ttl: P1D
                        length: 16
                        field_name: passwordResetToken
                    pin:
                        length: 4
                        field_name: passwordResetToken
                verification:
                    token:
                        length: 16
                        field_name: emailVerificationToken
#        shop:
#            user:
#                classes:
#                    model: Sylius\Component\Core\Model\ShopUser
#                    repository: Sylius\Bundle\CoreBundle\Doctrine\ORM\UserRepository
#                    form: Sylius\Bundle\CoreBundle\Form\Type\User\ShopUserType
#                    interface: Sylius\Component\User\Model\UserInterface
#                    controller: Sylius\Bundle\UserBundle\Controller\UserController
#                    factory: Sylius\Component\Resource\Factory\Factory
#                templates: 'SyliusUserBundle:User'
#                resetting:
#                    token:
#                        ttl: P1D
#                        length: 16
#                        field_name: passwordResetToken
#                    pin:
#                        length: 4
#                        field_name: passwordResetToken
#                verification:
#                    token:
#                        length: 16
#                        field_name: emailVerificationToken
        oauth:
            user:
                classes:
                    model: Sylius\Component\User\Model\UserOAuth
                    interface: Sylius\Component\User\Model\UserOAuthInterface
                    controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
                    factory: Sylius\Component\Resource\Factory\Factory
                    form: Sylius\Bundle\UserBundle\Form\Type\UserType
                templates: 'SyliusUserBundle:User'
                resetting:
                    token:
                        ttl: P1D
                        length: 16
                        field_name: passwordResetToken
                    pin:
                        length: 4
                        field_name: passwordResetToken
                verification:
                    token:
                        length: 16
                        field_name: emailVerificationToken