imports:
    # ##########################################################################
    #
    # SilCRMBundle
    #
    # ##########################################################################
    #
    #   Global file
    #
    - { resource: "@SilCRMBundle/Resources/config/admin.yml" }

    #   Single files
    #
    # - { resource: "@SilCRMBundle/Resources/config/admin/sil_crm.admin.organism_phone.yml" }
    # - { resource: "@SilCRMBundle/Resources/config/admin/sil_crm.admin.category.yml" }
    # - { resource: "@SilCRMBundle/Resources/config/admin/sil_crm.admin.role.yml" }
    # - { resource: "@SilCRMBundle/Resources/config/admin/sil_crm.admin.organism_group.yml" }
    # - { resource: "@SilCRMBundle/Resources/config/admin/sil_crm.admin.circle.yml" }
    # - { resource: "@SilCRMBundle/Resources/config/admin/sil_crm.admin.position.yml" }
    # - { resource: "@SilCRMBundle/Resources/config/admin/sil_crm.admin.position_type.yml" }
    # - { resource: "@SilCRMBundle/Resources/config/admin/sil_crm.admin.phone_type.yml" }
    # - { resource: "@SilCRMBundle/Resources/config/admin/sil_crm.admin.city.yml" }
    #
    # #   Override files
    # #
    # - { resource: "@PlatformBundle/Resources/config/admin/platform_crm.admin.individual.yml" }
    # - { resource: "@PlatformBundle/Resources/config/admin/platform_crm.admin.organization.yml" }
    # - { resource: "@PlatformBundle/Resources/config/admin/platform_crm.admin.organism.yml" }
    # - { resource: "@PlatformBundle/Resources/config/admin/platform_crm.admin.organism_embedded.yml" }
    # - { resource: "@PlatformBundle/Resources/config/admin/platform_crm.admin.customer.yml" }
    # - { resource: "@PlatformBundle/Resources/config/admin/platform_crm.admin.address.yml" }

    # ##########################################################################
    #
    # SilEcommerceBundle
    #
    # ##########################################################################

    #- { resource: "@SilEcommerceBundle/Resources/config/admin.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.channel_pricing.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.channel.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.customer_group.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.customer.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.invoice.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.order.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.payment_method.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.payment.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.product_attribute.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.product_variant_embedded.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.product_variant.yml" }
    #- { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.product.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.sales_journal.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.shipping_method_translation.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.shipping_method.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.shop_user.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.tax_category.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.taxon.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.tax_rate.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.zone.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.product_option.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.product_option_value.yml" }

    # ##########################################################################
    #
    # SilEmailBundle
    #
    # ##########################################################################

    - { resource: "@SilEmailBundle/Resources/config/admin.yml" }

    # ##########################################################################
    #
    # SilEmailCRMBundle
    #
    # ##########################################################################

    - { resource: "@SilEmailCRMBundle/Resources/config/admin.yml" }

    # ##########################################################################
    #
    # SilManufacturingBundle
    #
    # ##########################################################################

    - { resource: "@SilManufacturingBundle/Resources/config/admin.yml" }

    # ##########################################################################
    #
    # SilSonataSyliusUserBundle
    #
    # ##########################################################################

    - { resource: "@SilSonataSyliusUserBundle/Resources/config/admin.yml" }

    # ##########################################################################
    #
    # SilStockBundle
    #
    # ##########################################################################

    #- { resource: "@SilStockBundle/Resources/config/admin.yml" }
    #- { resource: "@SilStockBundle/Resources/config/admin/sil_stock.admin.stock_item.yml" }
    - { resource: "@SilStockBundle/Resources/config/admin/sil_stock.admin.movement.yml" }
    - { resource: "@SilStockBundle/Resources/config/admin/sil_stock.admin.operation.yml" }
    - { resource: "@SilStockBundle/Resources/config/admin/sil_stock.admin.warehouse.yml" }
    - { resource: "@SilStockBundle/Resources/config/admin/sil_stock.admin.location.yml" }
    - { resource: "@SilStockBundle/Resources/config/admin/sil_stock.admin.uom.yml" }
    - { resource: "@SilStockBundle/Resources/config/admin/sil_stock.admin.uom_type.yml" }
    - { resource: "@SilStockBundle/Resources/config/admin/sil_stock.admin.stock_unit.yml" }

    # ##########################################################################
    #
    # PlatformBundle
    #
    # ##########################################################################

    - { resource: "@PlatformBundle/Resources/config/admin/product.yml" }
