parameters:
    sil_crm.entity.address.class:                       PlatformBundle\Entity\SilCRMBundle\Address
    #sil.model.crm_organism.class:                      PlatformBundle\Entity\SilCRMBundle\Organism

    #sil_stock.entity.partner.class:                     "%sil.model.crm_organism.class%"
    sil_stock.entity.stock_item.class:                  "%sil_ecommerce.entity.product.class%"

    sil_ecommerce.entity.product.class:                 Sil\Bundle\EcommerceBundle\Entity\Product
    sil_ecommerce.entity.order.class:                   Sil\Bundle\EcommerceBundle\Entity\Order
    sil_ecommerce.entity.product_variant.class:         Sil\Bundle\EcommerceBundle\Entity\ProductVariant
    sil_ecommerce.entity.product_option_value.class:    Sil\Bundle\EcommerceBundle\Entity\ProductOptionValue

    sil_media.entity.file.class:                        PlatformBundle\Entity\SilMediaBundle\File

    sil_email.entity.email.class:                       PlatformBundle\Entity\SilEmailBundle\Email

    sil_sonata_sylius_user.entity.sonata_user.class:    PlatformBundle\Entity\SilSonataSyliusUserBundle\SonataUser
    sil_sonata_sylius_user.entity.sonata_group.class:   Sil\Bundle\SonataSyliusUserBundle\Entity\SonataGroup
