imports:
    - { resource: "@SyliusCoreBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusShopBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusAdminApiBundle/Resources/config/app/config.yml" }

    - { resource: "@BlastUtilsBundle/Resources/config/sonata.yml" }
    - { resource: "@BlastCoreBundle/Resources/config/config.yml" }
    - { resource: "@BlastResourceBundle/Resources/config/app/config.yml" }
    - { resource: "@SilMediaBundle/Resources/config/app/config.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/app/config.yml" }
    - { resource: "@SilCRMBundle/Resources/config/app/config.yml" }
    - { resource: "@SilEmailBundle/Resources/config/app/config.yml" }
    - { resource: "@SilSeedBatchBundle/Resources/config/app/config.yml" }
    - { resource: "@SilSonataSyliusUserBundle/Resources/config/app/config.yml" }
    - { resource: "@SilSyliusPayboxBundle/Resources/config/app/config.yml" }

    - { resource: "@SilStockBundle/Resources/config/app/config.yml" }
    - { resource: "@SilStockBundle/Resources/config/services.yml" }
    - { resource: "@SilStockBundle/Resources/config/admin.yml" }
    - { resource: "@SilManufacturingBundle/Resources/config/app/config.yml" }
    - { resource: "@SilManufacturingBundle/Resources/config/services.yml" }
    - { resource: "@SilManufacturingBundle/Resources/config/admin.yml" }


    - { resource: "@LisemBundle/Resources/config/varieties.yml" }
    - { resource: "@LisemBundle/Resources/config/sonata.yml" }
    - { resource: "@LisemBundle/Resources/config/services.yml" }
    - { resource: "@LisemBundle/Resources/config/sylius-fixtures.yml" }
    - { resource: "@LisemBundle/Resources/config/grids.yml" }
    - { resource: "@LisemBundle/Resources/config/state_machine.yml" }

    - { resource: "@LisemBundle/Resources/config/admin.yml" }


# doctrine:
#     orm:
#         resolve_target_entities:
#             Sil\Bundle\StockBundle\Domain\Entity\PartnerInterface:  Sil\Bundle\CRMBundle\Entity\Organism


# sylius_resource:
#     resources:
#         blast.utils:
#             classes:
#                 model: Sil\Bundle\SonataSyliusUserBundle\Entity\SonataUser
#                 interface: Sil\Bundle\SonataSyliusUserBundle\Entity\SonataUserInterface

sylius_channel:
    driver: doctrine/orm
    resources:
        channel:
            classes:
                model: Sil\Bundle\EcommerceBundle\Entity\Channel

sylius_money:
    locale: fr
    currency: EUR

sylius_theme:
    sources:
        filesystem:
            enabled: true
            filename: composer.json
            directories:
                - "%kernel.root_dir%/themes"
    context: lisem.theme.context.channel_based       # theme context service id

sil_ecommerce:
    code_generator:
        product_variant: LisemBundle\CodeGenerator\ProductVariantCodeGenerator
        product_variant_embedded: LisemBundle\CodeGenerator\ProductVariantEmbeddedCodeGenerator

# sylius_customer:
#     driver: doctrine/orm
#     resources:
#         customer:
#             classes:
#                 model: Sil\Bundle\CRMBundle\Entity\Organism

sylius_mailer:
    sender_adapter: lisem.sylius.email_sender.adapter
    sender:
        name: My LISem Company
        address: no-reply@my-lisem-company.com
    emails:
        test_email:
            subject: A new movie {{ movie.title }} has been submitted
            template: LisemBundle:Email:testEmail.html.twig

blast_utils:
    features:
        customFilters:
            enabled: true

sonata_admin:
    templates:
        history_revision_timestamp: SonataIntlBundle:CRUD:history_revision_timestamp.html.twig
        user_block:                 SilSonataSyliusUserBundle:Admin/Block:user_block.html.twig
        add_block:                  SonataAdminBundle:Core:add_block.html.twig
        layout:                     BlastDecoratorBundle:Admin:layout.html.twig
        ajax:                       SonataAdminBundle::ajax_layout.html.twig
        dashboard:                  SonataAdminBundle:Core:dashboard.html.twig
        search:                     SonataAdminBundle:Core:search.html.twig
        list:                       BlastCoreBundle:CRUD:base_list.html.twig
        filter:                     SonataAdminBundle:Form:filter_admin_fields.html.twig
        show:                       BlastCoreBundle:CRUD:base_show.html.twig
        show_compare:               SonataAdminBundle:CRUD:show_compare.html.twig
        edit:                       BlastCoreBundle:CRUD:base_edit.html.twig
        preview:                    SonataAdminBundle:CRUD:preview.html.twig
        history:                    SonataAdminBundle:CRUD:history.html.twig
        acl:                        SonataAdminBundle:CRUD:acl.html.twig
        action:                     SonataAdminBundle:CRUD:action.html.twig
        select:                     SonataAdminBundle:CRUD:list__select.html.twig
        list_block:                 SonataAdminBundle:Block:block_admin_list.html.twig
        search_result_block:        SonataAdminBundle:Block:block_search_result.html.twig
        short_object_description:   SonataAdminBundle:Helper:short-object-description.html.twig
        delete:                     SonataAdminBundle:CRUD:delete.html.twig
        batch:                      SonataAdminBundle:CRUD:list__batch.html.twig
        batch_confirmation:         SonataAdminBundle:CRUD:batch_confirmation.html.twig
        inner_list_row:             SonataAdminBundle:CRUD:list_inner_row.html.twig
        outer_list_rows_mosaic:     SonataAdminBundle:CRUD:list_outer_rows_mosaic.html.twig
        outer_list_rows_list:       SonataAdminBundle:CRUD:list_outer_rows_list.html.twig
        outer_list_rows_tree:       SonataAdminBundle:CRUD:list_outer_rows_tree.html.twig
        base_list_field:            SonataAdminBundle:CRUD:base_list_field.html.twig
        pager_links:                SonataAdminBundle:Pager:links.html.twig
        pager_results:              SonataAdminBundle:Pager:results.html.twig
        tab_menu_template:          SonataAdminBundle:Core:tab_menu_template.html.twig
        knp_menu_template:          SonataAdminBundle:Menu:sonata_menu.html.twig
        action_create:              SonataAdminBundle:CRUD:dashboard__action_create.html.twig
        button_acl:                 SonataAdminBundle:Button:acl_button.html.twig
        button_create:              SonataAdminBundle:Button:create_button.html.twig
        button_edit:                SonataAdminBundle:Button:edit_button.html.twig
        button_history:             SonataAdminBundle:Button:history_button.html.twig
        button_list:                SonataAdminBundle:Button:list_button.html.twig
        button_show:                SonataAdminBundle:Button:show_button.html.twig

sil_crm:
    Circle:
        allow_positions: false  # default: false
        app_circles:
            -
                id: "d474c5df-49fa-460b-8951-dafff97bbfc4"
                code: "OC"
                name: "Organic Certificator"
                createdAt: "2017-04-18 18:02:02"
                type: "Autres"
            -
                id: "15af43f3-d41a-4b41-aca5-3e606af348d3"
                code: "JAP"
                name: "Jardiniers particuliers"
                createdAt: "2017-06-16 09:34:45"
                type: "Client"
            -
                id: "19c612b4-5057-4b68-9ab1-c6f037325c2a"
                code: "REV"
                name: "Revendeurs"
                createdAt: "2017-06-16 09:34:45"
                type: "Client"
            -
                id: "30405c5a-92ee-4307-9272-933df540207c"
                code: "MAR"
                name: "Maraichers"
                createdAt: "2017-06-16 09:34:45"
                type: "Client"
            -
                id: "aeef530e-63d7-4c9c-9904-5bb5c0913d44"
                code: "PAM"
                name: "Producteur aromatique"
                createdAt: "2017-06-16 09:34:45"
                type: "Client"
            -
                id: "fa1c96e1-8771-4c19-bd69-a81129c1d6e5"
                code: "PRP"
                name: "Producteur de plants"
                createdAt: "2017-06-16 09:34:45"
                type: "Client"
            -
                id: "8afb9575-4194-4b2b-aac7-3f80534d97a4"
                code: "PRF"
                name: "Professionnel"
                createdAt: "2017-06-16 09:34:45"
                type: "Client"
            -
                id: "568ced20-9356-4406-9bec-79d9a6ddb364"
                code: "SEM"
                name: "Semencier"
                createdAt: "2017-06-16 09:34:45"
                type: "Autres"
            -
                id: "d43330ff-b35e-4e9a-9386-ede38a9bac3c"
                code: "ASS"
                name: "Associations"
                createdAt: "2017-06-16 09:34:45"
                type: "Client"
            -
                id: "30db8307-c998-49d9-8b94-79c4ef47125c"
                code: "COL"
                name: "Collectivités territoriales"
                createdAt: "2017-06-16 09:34:45"
                type: "Client"
            -
                id: "d7418a43-0ec2-4a5f-a007-ca609266e3ca"
                code: "SEF"
                name: "Semencier fournisseur de semences"
                createdAt: "2017-06-16 09:34:45"
                type: "Fournisseur"
            -
                id: "24c6a133-ffa2-4546-8bfc-7c1c3b2fe5df"
                code: "COD"
                name: "Contacts divers"
                createdAt: "2017-06-16 09:34:45"
                type: "Autres"
            -
                id: "f4a3c026-6787-430f-a821-c1ca6a4a7056"
                code: "PRS"
                name: "Prestataire de services"
                createdAt: "2017-06-16 09:34:45"
                type: "Autres"
            -
                id: "b70c9588-2c17-4ccb-8bce-ae943da81d0b"
                code: "FOU"
                name: "Fournisseurs"
                createdAt: "2017-06-16 09:34:45"
                type: "Fournisseur"
            -
                id: "58cbfc7b-cf37-4bce-849d-43b23eff8d75"
                code: "PAR"
                name: "Partenaires"
                createdAt: "2017-06-16 09:34:45"
                type: "Autres"
            -
                id: "34cf030b-9a84-4e79-acf6-082968b7aa16"
                code: "ASE"
                name: "Associés au capital de l'entreprise"
                createdAt: "2017-06-16 09:34:45"
                type: "Autres"
            -
                id: "c904af0e-53b0-4f84-bfec-f907873831fa"
                code: "ADM"
                name: "Administrations"
                createdAt: "2017-06-16 09:34:45"
                type: "Client"
            -
                id: "3046da7a-b373-4969-80cd-a06e609ec957"
                code: "ORC"
                name: "Organismes de contrôle"
                createdAt: "2017-06-16 09:34:45"
                type: "Autres"
            -
                id: "a6ffd7cc-33be-4ae6-9475-c1bc736863e5"
                code: "RSP"
                name: "Réseau semences paysannes"
                createdAt: "2017-06-16 09:34:45"
                type: "Autres"
            -
                id: "4e319aff-0f32-4bcd-a4f0-655ce84381c8"
                code: "CDC"
                name: "Croqueurs de Carottes"
                createdAt: "2017-06-16 09:34:45"
                type: "Autres"
            -
                id: "21f63609-f86c-43fc-a720-59d764d9bf79"
                code: "SAL"
                name: "Salariés"
                createdAt: "2017-06-16 09:34:45"
                type: "Autres"
            -
                id: "9c401554-b5f0-4ade-9760-172e320ca25a"
                code: "STA"
                name: "Stagiaires"
                createdAt: "2017-06-16 09:34:45"
                type: "Autres"
            -
                id: "f3b959e9-9904-4de2-ae0b-fe2ede88e422"
                code: "PRE"
                name: "Presse"
                createdAt: "2017-06-16 09:34:45"
                type: "Autres"
            -
                id: "79e7b5c1-1ab3-4ea4-8273-134493d93cd2"
                code: "FOI"
                name: "Foire"
                createdAt: "2017-06-16 09:34:45"
                type: "Autres"
            -
                id: "d31cb244-bee4-43a3-ad74-988598d49ca2"
                code: "ESS"
                name: "Essais / tests"
                createdAt: "2017-06-16 09:34:45"
                type: "Autres"
            -
                id: "7e690a34-2a07-401b-9e49-e7f2e3d3f2c0"
                code: "AMI"
                name: "Amis médiateur"
                createdAt: "2017-06-16 09:34:45"
                type: "Autres"
            -
                id: "37630a06-b4bd-4659-929e-b6af10d70abc"
                code: "SIT"
                name: "Site relais"
                createdAt: "2017-06-16 09:34:45"
                type: "Autres"
            -
                id: "b907691c-963f-4a7c-9098-5a95335cf21d"
                code: "PRO"
                name: "Producteur de semences"
                createdAt: "2017-04-18 18:02:02"
                type: "Producteur"
