sylius_channel:
    driver: doctrine/orm
    resources:
        channel:
            classes:
                model: Sil\Bundle\EcommerceBundle\Entity\Channel

sylius_money:
    locale: fr
    currency: EUR

sil_ecommerce:
    code_generator:
        product_variant: LisemBundle\CodeGenerator\ProductVariantCodeGenerator
        product_variant_embedded: LisemBundle\CodeGenerator\ProductVariantEmbeddedCodeGenerator

sylius_mailer:
    sender_adapter: lisem.sylius.email_sender.adapter
    sender:
        name: My LISem Company
        address: no-reply@my-lisem-company.com
    emails:
        test_email:
            subject: A new movie {{ movie.title }} has been submitted
            template: LisemBundle:Email:testEmail.html.twig

sylius_product:
    driver: doctrine/orm
    resources:
        product:
            classes:
                interface: Sylius\Component\Product\Model\ProductInterface
                model: LisemBundle\Entity\SilEcommerceBundle\Product
        product_variant:
            classes:
                model: LisemBundle\Entity\SilEcommerceBundle\ProductVariant
        product_option:
            classes:
                model: Sil\Bundle\EcommerceBundle\Entity\ProductOption
        product_option_value:
            classes:
                model: LisemBundle\Entity\SilEcommerceBundle\ProductOptionValue

sylius_attribute:
    resources:
        product:
            subject: LisemBundle\Entity\SilEcommerceBundle\Product
            attribute:
                classes:
                    model: Sil\Bundle\EcommerceBundle\Entity\ProductAttribute

sylius_order:
    resources:
        order:
            classes:
                model: LisemBundle\Entity\SilEcommerceBundle\Order
        order_item:
            classes:
                model: Sil\Bundle\EcommerceBundle\Entity\OrderItem
                controller: Sil\Bundle\EcommerceBundle\Controller\SyliusOrderItemController

sil_crm:
    Circle:
        allow_positions: false  # default: false
        app_circles:
            -
                id: "d474c5df-49fa-460b-8951-dafff97bbfc4"
                code: "OC"
                name: "Organic Certificator"
                createdAt: "2017-04-18 18:02:02"
                type: "Autres"
            -
                id: "15af43f3-d41a-4b41-aca5-3e606af348d3"
                code: "JAP"
                name: "Jardiniers particuliers"
                createdAt: "2017-06-16 09:34:45"
                type: "Client"
            -
                id: "19c612b4-5057-4b68-9ab1-c6f037325c2a"
                code: "REV"
                name: "Revendeurs"
                createdAt: "2017-06-16 09:34:45"
                type: "Client"
            -
                id: "30405c5a-92ee-4307-9272-933df540207c"
                code: "MAR"
                name: "Maraichers"
                createdAt: "2017-06-16 09:34:45"
                type: "Client"
            -
                id: "aeef530e-63d7-4c9c-9904-5bb5c0913d44"
                code: "PAM"
                name: "Producteur aromatique"
                createdAt: "2017-06-16 09:34:45"
                type: "Client"
            -
                id: "fa1c96e1-8771-4c19-bd69-a81129c1d6e5"
                code: "PRP"
                name: "Producteur de plants"
                createdAt: "2017-06-16 09:34:45"
                type: "Client"
            -
                id: "8afb9575-4194-4b2b-aac7-3f80534d97a4"
                code: "PRF"
                name: "Professionnel"
                createdAt: "2017-06-16 09:34:45"
                type: "Client"
            -
                id: "568ced20-9356-4406-9bec-79d9a6ddb364"
                code: "SEM"
                name: "Semencier"
                createdAt: "2017-06-16 09:34:45"
                type: "Autres"
            -
                id: "d43330ff-b35e-4e9a-9386-ede38a9bac3c"
                code: "ASS"
                name: "Associations"
                createdAt: "2017-06-16 09:34:45"
                type: "Client"
            -
                id: "30db8307-c998-49d9-8b94-79c4ef47125c"
                code: "COL"
                name: "Collectivités territoriales"
                createdAt: "2017-06-16 09:34:45"
                type: "Client"
            -
                id: "d7418a43-0ec2-4a5f-a007-ca609266e3ca"
                code: "SEF"
                name: "Semencier fournisseur de semences"
                createdAt: "2017-06-16 09:34:45"
                type: "Fournisseur"
            -
                id: "24c6a133-ffa2-4546-8bfc-7c1c3b2fe5df"
                code: "COD"
                name: "Contacts divers"
                createdAt: "2017-06-16 09:34:45"
                type: "Autres"
            -
                id: "f4a3c026-6787-430f-a821-c1ca6a4a7056"
                code: "PRS"
                name: "Prestataire de services"
                createdAt: "2017-06-16 09:34:45"
                type: "Autres"
            -
                id: "b70c9588-2c17-4ccb-8bce-ae943da81d0b"
                code: "FOU"
                name: "Fournisseurs"
                createdAt: "2017-06-16 09:34:45"
                type: "Fournisseur"
            -
                id: "58cbfc7b-cf37-4bce-849d-43b23eff8d75"
                code: "PAR"
                name: "Partenaires"
                createdAt: "2017-06-16 09:34:45"
                type: "Autres"
            -
                id: "34cf030b-9a84-4e79-acf6-082968b7aa16"
                code: "ASE"
                name: "Associés au capital de l'entreprise"
                createdAt: "2017-06-16 09:34:45"
                type: "Autres"
            -
                id: "c904af0e-53b0-4f84-bfec-f907873831fa"
                code: "ADM"
                name: "Administrations"
                createdAt: "2017-06-16 09:34:45"
                type: "Client"
            -
                id: "3046da7a-b373-4969-80cd-a06e609ec957"
                code: "ORC"
                name: "Organismes de contrôle"
                createdAt: "2017-06-16 09:34:45"
                type: "Autres"
            -
                id: "a6ffd7cc-33be-4ae6-9475-c1bc736863e5"
                code: "RSP"
                name: "Réseau semences paysannes"
                createdAt: "2017-06-16 09:34:45"
                type: "Autres"
            -
                id: "4e319aff-0f32-4bcd-a4f0-655ce84381c8"
                code: "CDC"
                name: "Croqueurs de Carottes"
                createdAt: "2017-06-16 09:34:45"
                type: "Autres"
            -
                id: "21f63609-f86c-43fc-a720-59d764d9bf79"
                code: "SAL"
                name: "Salariés"
                createdAt: "2017-06-16 09:34:45"
                type: "Autres"
            -
                id: "9c401554-b5f0-4ade-9760-172e320ca25a"
                code: "STA"
                name: "Stagiaires"
                createdAt: "2017-06-16 09:34:45"
                type: "Autres"
            -
                id: "f3b959e9-9904-4de2-ae0b-fe2ede88e422"
                code: "PRE"
                name: "Presse"
                createdAt: "2017-06-16 09:34:45"
                type: "Autres"
            -
                id: "79e7b5c1-1ab3-4ea4-8273-134493d93cd2"
                code: "FOI"
                name: "Foire"
                createdAt: "2017-06-16 09:34:45"
                type: "Autres"
            -
                id: "d31cb244-bee4-43a3-ad74-988598d49ca2"
                code: "ESS"
                name: "Essais / tests"
                createdAt: "2017-06-16 09:34:45"
                type: "Autres"
            -
                id: "7e690a34-2a07-401b-9e49-e7f2e3d3f2c0"
                code: "AMI"
                name: "Amis médiateur"
                createdAt: "2017-06-16 09:34:45"
                type: "Autres"
            -
                id: "37630a06-b4bd-4659-929e-b6af10d70abc"
                code: "SIT"
                name: "Site relais"
                createdAt: "2017-06-16 09:34:45"
                type: "Autres"
            -
                id: "b907691c-963f-4a7c-9098-5a95335cf21d"
                code: "PRO"
                name: "Producteur de semences"
                createdAt: "2017-04-18 18:02:02"
                type: "Producteur"
