# Copyright (C) 2015-2017 Libre Informatique
#
# This file is licenced under the GNU GPL v3.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

sonata_sylius_user_login:
    path: /login
    defaults:
        _controller: sylius.controller.user_security:loginAction
        _sylius:
            template: SilSonataSyliusUserBundle:Security:login.html.twig
            permission: true

sonata_sylius_user_login_check:
    path: /login-check
    defaults:
        _controller: sylius.controller.user_security:checkAction

sonata_sylius_user_logout:
    path: /logout
