
services:
    sil_variety.admin.variety_description_amateur:
        class: Sil\Bundle\VarietyBundle\Admin\VarietyDescriptionAdmin
        arguments: [~, "%sil_variety.entity.variety_description_amateur.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.variety.menu_label.variety_description_amateur
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
