
services:
    lisem.admin.other_product_variant:
        class: LisemBundle\Admin\OtherProductVariantAdmin
        arguments: [~, "%sil_ecommerce.entity.product_variant.class%", SilEcommerceBundle:ProductVariantCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: lisem.lisembundle.admin.other_product_variant
              label_translator_strategy: blast.resource.sonata.label_strategy.prefix
        calls:
            - [ setTemplate, [ edit, SilEcommerceBundle:ProductVariantAdmin:edit.html.twig ] ]
