
services:
    lisem.admin.packaging:
        class: LisemBundle\Admin\PackagingAdmin
        arguments: [~, "%sil_ecommerce.entity.product_option_value.class%", LisemBundle:PackagingCRUD ]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: lisem.lisembundle.admin.packaging
              label_translator_strategy: blast.resource.sonata.label_strategy.prefix
        calls:
            - [ setTemplate, [ edit, LisemBundle:PackagingAdmin:edit.html.twig ] ]
