services:
### TWIG EXTENSIONS ###
    sil_media.twig_extension.img_tag_generator:
        class: Sil\Bundle\MediaBundle\Twig\Extension\GenerateImgTagExtension
        tags:
            - { name: twig.extension }
### FORM TYPES ###
    sil_media.form.type.dropzone:
        class: Sil\Bundle\MediaBundle\Form\Type\DropzoneType
        tags:
            - { name: form.type, alias: sil_dropzone }

    imagine.data.loader.db_loader:
        class: Sil\Bundle\MediaBundle\Imagine\Loader\DbLoader
        arguments:
            - "@imagine.data.loader.resolver.default"
            - "@liip_imagine"
        calls:
            - [setEm, ['@doctrine.orm.entity_manager'] ]
        tags:
            - { name: "liip_imagine.binary.loader", loader: db_loader }

    imagine.data.loader.resolver.abstract:
        abstract: true
        class: Sil\Bundle\MediaBundle\Imagine\PathResolver\DefaultResolver
        calls:
            - [setEm, ['@doctrine.orm.entity_manager'] ]
            - [setWebDir, ['%kernel.project_dir%/%symfony-web-dir%'] ]

    imagine.data.loader.resolver.default:
        parent: imagine.data.loader.resolver.abstract
        class: Sil\Bundle\MediaBundle\Imagine\PathResolver\DefaultResolver

    sil_media.events.listener:
        class: Sil\Bundle\MediaBundle\Events\UploadControllerEventListener
        calls:
            - [setEm, ["@doctrine.orm.entity_manager"]]
        tags:
            - { name: kernel.event_listener, event: sil.events.media.load.preGetEntity, method: preGetEntity, priority: 0 }
            - { name: kernel.event_listener, event: sil.events.media.load.postGetEntity, method: postGetEntity, priority: 0 }
