Sil\Bundle\SeedBatchBundle\Entity\CertificationType:
    type: entity
    table: lisem_seed_batch_certification_type
    fields:
        code:
            type: string
            length: 255
            unique: true

    oneToOne:
        logo:
            targetEntity: Sil\Bundle\MediaBundle\Entity\FileInterface
            joinColumn:
                name: logo_id
                referencedColumnName: id
                nullable: true
                onDelete: SET NULL
            cascade: [persist, remove]
            oprhanRemoval: true
