Sil\Bundle\SeedBatchBundle\Entity\CertifyingBody:
    type: entity

    fields:
        code:
            type:       string(255)
            nullable:   true
        url:
            type:       string(255)
            nullable:   true

