Sil\Bundle\StockBundle\Domain\Entity\OutputStrategy:
    type: mappedSuperclass
    table: sil_stock_output_strategy
    fields:
        name:
            type: string(255)
            unique: true
            nullable: false
        description:
            type: string(255)
            nullable: true
        orderBy:
            type: array
            nullable: false
