parameters:
    sonata.core.flashmessage.manager.class: Sil\Bundle\EcommerceBundle\Services\FlashManager

imports:
     - { resource: '@SilEcommerceBundle/Resources/config/vendor/blast/resource.yml' }
     - { resource: '@SilEcommerceBundle/Resources/config/vendor/blast/menu.yml' }
     - { resource: "@SilEcommerceBundle/Resources/config/app/state_machine.yml" }

doctrine:
    orm:
        mappings:


sylius_product:
    driver: doctrine/orm
    resources:
        product:
            classes:
                model: "%sil.model.ecommerce_product.class%"
        product_variant:
            classes:
                model: "%sil.model.ecommerce_product_variant.class%"
        product_option:
            classes:
                model: "%sil.model.ecommerce_product_option.class%"
        product_option_value:
            classes:
                model: "%sil.model.ecommerce_product_option_value.class%"

sylius_review:
    resources:
        product:
            subject: "%sylius.model.product.class%"
            review:
                classes:
                    model: "%sil.model.ecommerce_product_review.class%"

sylius_order:
    resources:
        order:
            classes:
                model: "%sil.model.ecommerce_order.class%"
        order_item:
            classes:
                model: "%sil.model.ecommerce_order_item.class%"
                controller: Sil\Bundle\EcommerceBundle\Controller\SyliusOrderItemController

sylius_taxation:
    resources:
        tax_rate:
            classes:
                model: "%sil.model.ecommerce_tax_rate.class%"


sylius_channel:
    driver: doctrine/orm
    resources:
        channel:
            classes:
                model: "%sil.model.ecommerce_channel.class%"
                repository: Sil\Bundle\EcommerceBundle\Repository\ChannelRepository

sylius_attribute:
    resources:
        product:
            subject: "%sil.model.ecommerce_product.class%"
            attribute:
                classes:
                    model: "%sil.model.ecommerce_product_attribute.class%"

sylius_customer:
    driver: doctrine/orm
    resources:
        customer_group:
            classes:
                model: "%sil.model.ecommerce_customer_group.class%"

sylius_addressing:
    resources:
        zone:
            classes:
                model: "%sil.model.ecommerce_zone.class%"

sylius_core:
    resources:
        product_image:
            classes:
                model: "%sil.model.ecommerce_product_image.class%"

sylius_taxonomy:
    resources:
        taxon:
            classes:
                model: "%sil.model.ecommerce_taxon.class%"

sylius_shipping:
    driver: doctrine/orm
    resources:
        shipping_method:
            classes:
                model: "%sil.model.ecommerce_shipping_method.class%"

sylius_payment:
    driver: doctrine/orm
    resources:
        payment:
            classes:
                model: "%sil.model.ecommerce_payment.class%"

sylius_shop:
    checkout_resolver:
        pattern: /checkout/.+
        route_map:
            empty_order:
                route: sylius_shop_cart_summary
            cart:
                route: sylius_shop_checkout_address_override
            addressed:
                route: sylius_shop_checkout_select_shipping
            shipping_selected:
                route: sylius_shop_checkout_select_payment
            shipping_skipped:
                route: sylius_shop_checkout_select_payment
            payment_selected:
                route: sylius_shop_checkout_complete
            payment_skipped:
                route: sylius_shop_checkout_complete

fos_rest:
    exception: ~
    view:
        formats:
            json: true
            xml:  true
        empty_content: 204

liip_imagine:
    filter_sets:
        sylius_shop_product_original: ~
        sylius_shop_product_tiny_thumbnail:
            filters:
                thumbnail: { size: [64, 64], mode: outbound, allow_upscale: true }
        sylius_shop_product_small_thumbnail:
            filters:
                thumbnail: { size: [150, 112], mode: outbound, allow_upscale: true }
        sylius_shop_product_thumbnail:
            filters:
                thumbnail: { size: [260, 260], mode: outbound, allow_upscale: true }
        sylius_shop_product_large_thumbnail:
            filters:
                thumbnail: { size: [550, 412], mode: outbound, allow_upscale: true }

knp_snappy:
    #process_timeout: 20 # In seconds
    pdf:
        enabled: true
        binary:  '%kernel.project_dir%/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64'
        options: []
    image:
        enabled: false
        binary:  '%kernel.project_dir%/vendor/h4cc/wkhtmltoimage-amd64/bin/wkhtmltoimage-amd64'
        options: []
