imports:
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.channel_pricing.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.channel.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.customer_group.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.customer.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.invoice.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.order.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.payment_method.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.payment.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.product_attribute.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.product_variant_embedded.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.product_variant.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.product.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.sales_journal.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.shipping_method_translation.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.shipping_method.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.shop_user.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.tax_category.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.taxon.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.tax_rate.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce.admin.zone.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce_option.admin.product.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/admin/sil_ecommerce_option_value.admin.product.yml" }
