imports:
     - { resource: "dashboard.yml" }

parameters:
    sylius.form.type.checkout_address.validation_groups:
        - sil_ecommerce_organism
        - sil_ecommerce_address
    sylius.form.type.address.validation_groups:
        - sil_ecommerce_organism
        - sil_ecommerce_address

services:

# ENTITY CODE GENERATORS
    sil_ecommerce.code_generator.product:
        class: Sil\Bundle\EcommerceBundle\CodeGenerator\ProductCodeGenerator
        factory:   ['@blast_core.code_generator_factory', create]
        arguments: ['%sil_ecommerce.code_generator.product%', '@doctrine.orm.entity_manager']
        tags:
            - { name: blast.entity_code_generator }

    sil_ecommerce.code_generator.product_variant:
        class: Sil\Bundle\EcommerceBundle\CodeGenerator\ProductVariantCodeGenerator
        factory:   ['@blast_core.code_generator_factory', create]
        arguments: ['%sil_ecommerce.code_generator.product_variant%', '@doctrine.orm.entity_manager']
        tags:
            - { name: blast.entity_code_generator }

    sil_ecommerce.code_generator.invoice:
        class: Sil\Bundle\EcommerceBundle\CodeGenerator\InvoiceCodeGenerator
        factory:   ['@blast_core.code_generator_factory', create]
        arguments: ['%sil_ecommerce.code_generator.invoice%', '@doctrine.orm.entity_manager']
        tags:
            - { name: blast.entity_code_generator }

# FORM TYPES

    sil_ecommerce.form.type.order_state:
        class: Sil\Bundle\EcommerceBundle\Form\Type\OrderStateType
        tags:
            - { name: form.type, alias: sil_type_order_state }

    sil_ecommerce.form.type.payment_state:
        class: Sil\Bundle\EcommerceBundle\Form\Type\PaymentStateType
        tags:
            - { name: form.type, alias: sil_type_payment_state }

    sil_ecommerce.form.type.shipping_state:
        class: Sil\Bundle\EcommerceBundle\Form\Type\ShippingStateType
        tags:
            - { name: form.type, alias: sil_type_shipping_state }

    sil_ecommerce.form.type.price_cents:
        class: Sil\Bundle\EcommerceBundle\Form\Type\PriceCentsType
        tags:
            - { name: form.type, alias: sil_type_price_cents }

    sil_ecommerce.form.type.taxon_list:
        class: Sil\Bundle\EcommerceBundle\Form\Type\TaxonListType
        tags:
            - { name: form.type, alias: sil_type_taxon_list }
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%sylius.model.taxon.class%'

    sil_ecommerce.form.type.product_taxon_list:
        class: Sil\Bundle\EcommerceBundle\Form\Type\ProductTaxonListType
        tags:
            - { name: form.type, alias: sil_type_product_taxon_list }
        arguments:
            # - '@property_accessor'
            - '@doctrine.orm.entity_manager'
            - '%sylius.model.product_taxon.class%'
            - '%sylius.model.taxon.class%'

    sil_ecommerce.form.type.product_channels:
        class: Sil\Bundle\EcommerceBundle\Form\Type\ProductChannelsType
        tags:
            - { name: form.type, alias: sil_type_product_channels }
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%sylius.model.channel.class%'
            - '%sylius.model.product.class%'


    sil_ecommerce.form.type.shipping_method_channels:
        class: Sil\Bundle\EcommerceBundle\Form\Type\ShippingMethodChannelsType
        tags:
            - { name: form.type, alias: sil_type_shipping_method_channels }
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%sylius.model.channel.class%'
            - '%sylius.model.shipping_method.class%'

# EMAIL MANAGERS

    sil_ecommerce.email_manager.order:
        class: Sil\Bundle\EcommerceBundle\EmailManager\OrderEmailManager
        arguments:
            - '@sylius.email_sender'
            - '@sil_ecommerce.order_invoice_manager'
            - '@doctrine.orm.entity_manager'

# ORDER MANAGERS

    sil_ecommerce.order_customer_manager:
        class: Sil\Bundle\EcommerceBundle\Services\OrderCustomerManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%sylius.model.customer.class%'

    sil_ecommerce.order_manager:
        class: Sil\Bundle\EcommerceBundle\Services\OrderManager
        arguments:
            - '@doctrine.orm.entity_manager'
        calls:
            - [setStateMachine, ['@sm.factory']]
            - [setOrderNumberAssigner, ['@sylius.order_number_assigner']]

    sil_ecommerce.order_invoice_manager:
        class: Sil\Bundle\EcommerceBundle\Services\OrderInvoiceManager
        arguments:
            - '@doctrine.orm.entity_manager'
        calls:
            - [setStateMachine, ['@sm.factory']]
            - [setInvoiceFactory, ['@sil_ecommerce.factory.invoice']]
            - [setSalesJournalService, ['@sil_ecommerce.sales_journal.service']]

# @TODO remove service_container and calls all the needed service

    sil_ecommerce.order_creation_manager:
        class: Sil\Bundle\EcommerceBundle\Services\OrderCreationManager
        arguments:
            - '@doctrine.orm.entity_manager'
        calls:

            - [setStateMachineFactory, ['@sm.factory']]
            - [setOrderItemFactory, ['@sylius.factory.order_item']]
            - [setOrderItemQuantityModifier, ['@sylius.order_item_quantity_modifier']]
            - [setOrderRepository, ['@sylius.repository.order']]
            - [setOrderManager, ['@sylius.manager.order']]
            - [setOrderNumberAssigner, ['@sylius.order_number_assigner']]
            - [setOrderFactory, ['@sylius.factory.order']]
            - [setAddressFactory, ['@sylius.factory.address']]
            - [setCustomerFactory, ['@sylius.factory.customer']]

# EVENT LISTENERS

    sil_ecommerce.listener.sylius_guidable:
        class: Sil\Bundle\EcommerceBundle\EventListener\SyliusGuidableListener
        tags:
            - { name: doctrine.event_subscriber, priority: -10 }
        calls:
            - [setLogger, ['@logger']]
            - [setClassAnalyser, [Blast\Bundle\CoreBundle\Tools\Reflection\ClassAnalyzer]]

    # service override
    sylius.listener.order_complete:
        class: Sil\Bundle\EcommerceBundle\EventListener\OrderCompleteListener
        tags:
            - { name: kernel.event_listener, event: sylius.order.post_complete, method: sendConfirmationEmail }
        arguments:
            - '@sil_ecommerce.email_manager.order'



# SYLIUS INSTALLER

    sil_ecommerce.sylius.setup.currency:
        class: Sil\Bundle\EcommerceBundle\Services\Sylius\Setup\CurrencySetup
        arguments:
            - '@sylius.repository.currency'
            - '@sylius.factory.currency'
            - '%currency%'

# SYLIUS FACTORIES

    sil_ecommerce.sylius.factory.customer:
        class: Sil\Bundle\EcommerceBundle\Factory\CustomerFactory
        decorates: 'sylius.factory.customer'
        arguments:
            - '%sylius.model.customer.class%'
            - '@sil_ecommerce.sylius.factory.customer.inner'
            - '@sil_crm.code_generator.customer'

    sil_ecommerce.factory.invoice:
        class: Sil\Bundle\EcommerceBundle\Factory\InvoiceFactory
        arguments:
            - '@sil_ecommerce.code_generator.invoice'
            - '@knp_snappy.pdf'
            - '@templating'
            - '%sil_ecommerce.invoice.template%'
            - '%kernel.root_dir%'

# SYLIUS FIXTURES & FIXTURE FACTORIES

    sil_ecommerce.sylius.fixture.channel:
        class: Sil\Bundle\EcommerceBundle\Fixture\ChannelFixture
        arguments:
            - '@sylius.manager.channel'
            - '@sil_ecommerce.sylius.fixture.example_factory.channel'
        tags:
            - { name: sylius_fixtures.fixture }

    sil_ecommerce.sylius.fixture.customer:
        class: Sil\Bundle\EcommerceBundle\Fixture\CustomerFixture
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@sil_crm.code_generator.customer'
        tags:
            - { name: sylius_fixtures.fixture }

    sil_ecommerce.sylius.fixture.example_factory.channel:
        class: Sil\Bundle\EcommerceBundle\Fixture\Factory\ChannelExampleFactory
        arguments:
            - '@sylius.factory.channel'
            - '@sylius.repository.locale'
            - '@sylius.repository.currency'
            - '@sylius.repository.zone'


# USER BUNDLE OVERRIDES

# TODO: refactor this since it does not work well with SonataSyliusUserBundle

#    sil_user.listener.traceable:
#        class: Sil\Bundle\EcommerceBundle\EventListener\TraceableListener
#        tags:
#            - { name: doctrine.event_subscriber }
#        calls:
#            - [setLogger,['@logger']]
#            - [setTokenStorage, ['@security.token_storage']]
#            - [setUserClass, [Sil\Bundle\EcommerceBundle\Entity\AdminUser]]
#            - [setClassAnalyser, [Blast\Bundle\CoreBundle\Tools\Reflection\ClassAnalyzer]]
#
#    sil_user.listener.ownable:
#        class: Sil\Bundle\SonataSyliusUserBundle\EventListener\OwnableListener
#        tags:
#            - { name: doctrine.event_subscriber }
#        calls:
#            - [setLogger,['@logger']]
#            - [setTokenStorage, ['@security.token_storage']]
#            - [setUserClass, [Sil\Bundle\EcommerceBundle\Entity\AdminUser]]
#            - [setClassAnalyser, [Blast\Bundle\CoreBundle\Tools\Reflection\ClassAnalyzer]]

    imagine.data.loader.resolver.default:
        class: Sil\Bundle\EcommerceBundle\Imagine\PathResolver\ProductPathResolver
        calls:
            - [setEm, ['@doctrine.orm.entity_manager'] ]
            - [setWebDir, ['%kernel.project_dir%/%symfony-web-dir%'] ]

    sil_ecommerce.media.events.listener:
        class: Sil\Bundle\EcommerceBundle\EventListener\UploadControllerEventListener
        calls:
            - [setEm, ["@doctrine.orm.entity_manager"]]
        tags:
            - { name: kernel.event_listener, event: sil.events.media.load.preGetEntity, method: preGetEntity, priority: 10 }
            - { name: kernel.event_listener, event: sil.events.media.load.postGetEntity, method: postGetEntity, priority: 10 }
            - { name: kernel.event_listener, event: sil.events.media.removeEntity, method: removeEntity, priority: 10 }

    sil_ecommerce.order.updater:
        class: Sil\Bundle\EcommerceBundle\Services\OrderUpdater
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@sylius.context.channel'
#            - '@sylius.money_formatter'
            - '@sylius.factory.order_item'
            - '@sylius.factory.order_item_unit'
            - '@sm.factory'
            - '@sylius.order_processing.order_processor.composite'

    sil_ecommerce.order.item_updater:
        class: Sil\Bundle\EcommerceBundle\Services\OrderItemUpdater
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@sylius.order_item_quantity_modifier'
            - '@sylius.money_formatter'
            - '%sylius.model.order_item.class%'
            - '@sm.factory'
            - '@translator'
            - '@sylius.order_processing.order_processor.composite'

    sil.ecommerce.filters.customer:
        class: Sil\Bundle\EcommerceBundle\Services\Filters\CustomerFilter

    sylius.controller.shop.homepage:
        class: Sil\Bundle\EcommerceBundle\Controller\SyliusHomepageController
        calls:
            - [setTemplating, ['@templating']]
            - [setChannelContext, ['@sylius.context.channel']]
            - [setFallbackChannelCode, ['%sylius_fallback_channel_code%']]

    sil.ecommerce.sylius_shop_request_listener:
        class: Sil\Bundle\EcommerceBundle\EventListener\SyliusRequestChannelContext
        calls:
            - [setFallbackChannelCode, ['%sylius_fallback_channel_code%']]
            - [setChannelRepository, ['@sylius.repository.channel']]
        tags:
            - { name: sylius.context.channel.request_based.resolver }

    sil_ecommerce.form.type.address_type_extension:
        class: Sil\Bundle\EcommerceBundle\Form\Type\Checkout\AddressTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\AddressingBundle\Form\Type\AddressType}

    sil_ecommerce.form.type.customer_guest_type_extension:
        class: Sil\Bundle\EcommerceBundle\Form\Type\Checkout\CustomerGuestTypeExtension
        calls:
            - [setValidator, ['@validator']]
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\CoreBundle\Form\Type\Customer\CustomerGuestType }

    sil_ecommerce.form.type.order_address_type:
        class: Sil\Bundle\EcommerceBundle\Form\Type\OrderAddressType
        calls:
            - [setAddressClass, ['%sylius.model.address.class%']]
        tags:
            - { name: form.type }

    sil_ecommerce.twig.shipment_cost:
        class: Sil\Bundle\EcommerceBundle\Twig\ShipmentCost
        calls:
            - [setShippingCalculator, ['@sylius.shipping_calculator']]
            - [setMoneyFormater, ['@sylius.money_formatter']]
        tags:
            - { name: twig.extension }

    sylius.provider.product_variants_prices:
        class: Sil\Bundle\EcommerceBundle\Services\ProductVariantsPricesProvider
        arguments: ["@sylius.calculator.product_variant_price"]

    sil_ecommerce.twig.product_variant_collection_helper:
        class: Sil\Bundle\EcommerceBundle\Twig\ProductVariantCollectionHelper
        tags:
            - { name: twig.extension }

    sil_ecommerce.order_item_quantity_modifier:
        class: Sil\Bundle\EcommerceBundle\Modifier\OrderItemQuantityModifier
        arguments: ["@sylius.factory.order_item_unit"]

    sil_ecommerce.order_item_quantity_modifier.limiting:
        class: Sil\Bundle\EcommerceBundle\Modifier\LimitingOrderItemQuantityModifier
        decorates: sylius.order_item_quantity_modifier.limiting
        decoration_priority: 254
        arguments: ["@sylius.order_item_quantity_modifier.limiting.inner", 9999]
        calls:
            - [setBulkOrderItemQuantityModifier,["@sil_ecommerce.order_item_quantity_modifier"]]

    sil_ecommerce.event_listener.sylius_order_item_controller:
        class: Sil\Bundle\EcommerceBundle\EventListener\SyliusOrderItemControllerListener
        tags:
            - { name: kernel.event_listener, event: sylius.order_item.pre_add, method: onOrderItemAddToCart }

    sil_ecommerce.listener.payement:
        class: Sil\Bundle\EcommerceBundle\EventListener\PaymentMappingListener
        calls:
            - [setLogger, ['@logger']]
            - [setClassAnalyser, [Blast\Bundle\CoreBundle\Tools\Reflection\ClassAnalyzer]]
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    sil_ecommerce.form.type.customer_guest_extension:
        class: Sil\Bundle\EcommerceBundle\Form\Type\CustomerGuestTypeExtension
        arguments:
            - '@sylius.repository.customer'
            - '@sylius.factory.customer'
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\CoreBundle\Form\Type\Customer\CustomerGuestType }

# SALES JOURNAL

    sil_ecommerce.sales_journal.service:
        class: Sil\Bundle\EcommerceBundle\SalesJournal\SalesJournalService
        calls:
            - [setSalesJournalItemFactory, ['@sil_ecommerce.sales_journal.sales_journal_item.factory']]
            - [setOrderHandler, ['@sil_ecommerce.sales_journal.handler.order_handler']]
            - [setPaymentHandler, ['@sil_ecommerce.sales_journal.handler.payment_handler']]

    sil_ecommerce.repository.sales_journal_item:
        class: Sil\Bundle\EcommerceBundle\Repository\SalesJournalItemRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Sil\Bundle\EcommerceBundle\Entity\SalesJournalItem

    sil_ecommerce.sales_journal.sales_journal_item.factory:
        class: Sil\Bundle\EcommerceBundle\SalesJournal\Factory\SalesJournalItemFactory

    sil_ecommerce.sales_journal.handler.abstract_handler:
        abstract: true
        calls:
            - [setSalesJournalItemFactory, ['@sil_ecommerce.sales_journal.sales_journal_item.factory']]
            - [setSalesJournalItemRepository, ['@sil_ecommerce.repository.sales_journal_item']]

    sil_ecommerce.sales_journal.handler.order_handler:
        parent: sil_ecommerce.sales_journal.handler.abstract_handler
        class: Sil\Bundle\EcommerceBundle\SalesJournal\Handler\OrderHandler
        calls:
            - [setOrderItemStrategy, ['@sil_ecommerce.sales_journal.strategy.order_item.strategy']]
            - [setOrderAdjustmentStrategy, ['@sil_ecommerce.sales_journal.strategy.order_adjustment.strategy']]
            - [setCustomerStrategy, ['@sil_ecommerce.sales_journal.strategy.customer.strategy']]

    sil_ecommerce.sales_journal.handler.payment_handler:
        parent: sil_ecommerce.sales_journal.handler.abstract_handler
        class: Sil\Bundle\EcommerceBundle\SalesJournal\Handler\PaymentHandler
        calls:
            - [setPaymentStrategy, ['@sil_ecommerce.sales_journal.strategy.payment.strategy']]
            - [setCustomerStrategy, ['@sil_ecommerce.sales_journal.strategy.customer.strategy']]

    sil_ecommerce.sales_journal.strategy.order_item.strategy:
        class: Sil\Bundle\EcommerceBundle\SalesJournal\Strategy\OrderItemStrategy

    sil_ecommerce.sales_journal.strategy.order_adjustment.strategy:
        class: Sil\Bundle\EcommerceBundle\SalesJournal\Strategy\OrderAdjustmentStrategy

    sil_ecommerce.sales_journal.strategy.payment.strategy:
        class: Sil\Bundle\EcommerceBundle\SalesJournal\Strategy\PaymentStrategy

    sil_ecommerce.sales_journal.strategy.customer.strategy:
        class: Sil\Bundle\EcommerceBundle\SalesJournal\Strategy\CustomerStrategy

    sylius.taxation.order_item_units_taxes_applicator:
        class:  Sil\Bundle\EcommerceBundle\Tax\OrderItemUnitsTaxesApplicator
        arguments:
            - "@sylius.tax_calculator"
            - "@sylius.factory.adjustment"
            - "@sylius.tax_rate_resolver"

    sylius.taxation.order_items_taxes_applicator:
        class: Sil\Bundle\EcommerceBundle\Tax\OrderItemsTaxesApplicator
        arguments:
            - "@sylius.tax_calculator"
            - "@sylius.factory.adjustment"
            - "@sylius.integer_distributor"
            - "@sylius.tax_rate_resolver"
