
Sil\Bundle\VarietyBundle\Entity\VarietyDescriptionProfessional:
    type: entity
    table: lisem_variety_description_professional
    manyToOne:
        variety:
            targetEntity: Sil\Bundle\VarietyBundle\Entity\VarietyInterface
            inversedBy: professional_descriptions
            joinColumn:
                name: variety_id
