blast_base_entities:
    entity_searchable_indexes:
        -
            class: '%sil_seed_batch.entity.seed_batch.class%'
            fields:
                - variety
                - producer
                - code
                - batchNumber
                - productionYear
