imports:
    - { resource: '@SilEmailBundle/Resources/config/vendor/blast/resource.yml' }
    - { resource: '@SilEmailBundle/Resources/config/vendor/blast/menu.yml' }

blast_base_entities:
    entity_searchable_indexes:
        -
            class: '%sil.model.email.class%'
            fields:
                - field_to
                - field_subject
                - textContent
                - sent
        -
            class: '%sil.model.email_email_template.class%'
            fields:
                - name
                - content
